{
 "title": "BPMN Execution Monitoring",
 "tags": [ "BPMN" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "BPMN commands (nodes) executed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bpmn_execution_commands[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(bpmn_execution_commands[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "BPMN Instances (processes) Started",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(bpmn_instances_started[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(bpmn_instances_started[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Command Consumer Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bpmn_queue_CommandConsumerQueue",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start on NATS Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "bpmn_queue_StartOnNatsMessages", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "BPMN Engine Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\".*bpmn.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_goroutines{instance=~\".*core.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands - Instances",
   "type": "timeseries",
   "description": "This is built for alerting, if it is every < 0 BPMN is failing to execute nodes on instances that have been created.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  }
 ]
}