{
 "title": "NATS Server Dashboard",
 "description": "NATS Server Dashboard for use with the Prometheus NATS Exporter",
 "tags": [
  "system-monitoring",
  "NATS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "gnatsd_varz_cpu{}", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "gnatsd_varz_mem", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "gnatsd_varz_in_bytes", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_in_msgs", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "gnatsd_varz_out_bytes", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_out_msgs", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "NATS Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnatsd_connz_pending_bytes",
     "legendFormat": "{{server_id}} - {{ type }} - {{ name }} ({{ cid }})"
    }
   ]
  },
  {
   "title": "NATS Route Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_routez_num_routes", "legendFormat": "{{server_id}} - {{instance}}" }
   ]
  },
  {
   "title": "Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Round Time Trips (RTT)",
   "type": "timeseries",
   "description": "The time it takes to make a round trip between the server and the connection. Less is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "gnatsd_connz_rtt",
     "legendFormat": "{{ server_id }} - {{ type }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_connz_subscriptions",
     "legendFormat": "{{server_id}}({{type}}) - {{name}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_slow_consumers", "legendFormat": "{{server_id}}" }
   ]
  },
  { "title": "Stream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Queue Monitoring NATS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "jetstream_stream_total_messages{stream_name=~\"KV_EquipmentVersion|KV_WorkflowSpecifications|OPCUA|KV_EquipmentProperty|KV_JobResponses|MKG|KV_MutationStatus|libreBpmn_command|LibreTimerStart\"}",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "NATS Stream Sizes (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jetstream_stream_total_bytes", "legendFormat": "{{ stream_name }}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "gnatsd_varz_slow_consumer_stats_clients",
     "legendFormat": "{{ server_id }} Slow Consumer Clients"
    },
    {
     "expr": "gnatsd_varz_slow_consumer_stats_gateways",
     "legendFormat": "{{ server_id }} Slow Consumer Gateways"
    },
    {
     "expr": "gnatsd_varz_slow_consumer_stats_routes",
     "legendFormat": "{{ server_id }} Slow Consumer Routes"
    },
    {
     "expr": "gnatsd_varz_slow_consumer_stats_leafs",
     "legendFormat": "{{ server_id }} Slow Consumer Leafs"
    }
   ]
  },
  {
   "title": "NATS Stream Msg Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jetstream_stream_total_messages",
     "legendFormat": "{{ stream_name }}"
    }
   ]
  }
 ]
}