{
 "title": "Storage Monitoring",
 "tags": [
  "kubernetes",
  "system-monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Volume Capacity",
   "type": "timeseries",
   "description": "Show the % Utilization of Storage capacity of each volume in the cluster.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim)\r\n  /\r\nsum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Node Storage Capacity",
   "type": "timeseries",
   "description": "Show the storage used as a % of each node. Note that Pod storage is different than Node storage. ",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persisted Volume Storage Delta",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes[10m]) / 600",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}